---
- name: Install screen
  become: true
  ansible.builtin.apt:
    name: screen
    state: present

- name: Copy .screenrc configuration
  ansible.builtin.copy:
    src: .screenrc
    dest: ~/.screenrc
    mode: "0644"
