---
- name: Add fastfetch PPA
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:zhangsongcui3371/fastfetch
    state: present
    update_cache: true

- name: Install fastfetch
  become: true
  ansible.builtin.apt:
    name: fastfetch
    state: present

- name: Deploy ASCII art for MOTD
  become: true
  ansible.builtin.copy:
    src: ascii.txt
    dest: /etc/neofetch-ascii.txt
    owner: root
    group: root
    mode: "0644"

- name: Deploy dynamic MOTD script
  become: true
  ansible.builtin.template:
    src: 10-machine0.j2
    dest: /etc/update-motd.d/00-machine0-header
    owner: root
    group: root
    mode: "0755"
